[alias]
myproject = "https://github.com/travisbhartwell/myproject-tool-plugin"
mycmd = "github:travisbhartwell/mycmd"

[tools]
mycmd = "latest"
myproject = "latest"
shellcheck = "latest"
shfmt = "latest"
uv = "latest"
