#!/usr/bin/env bash
# shellcheck shell=bash

set -o nounset -o errexit -o errtrace -o pipefail

[[ -z "${MYCMD_BASE_DIR-}" ]] && {
    echo >&2 "The script $0 should only be launched using 'mycmd'."
    exit 1
}

# shellcheck source=./mycmd/mycmd-lib
source "${MYCMD_BASE_DIR}/mycmd-lib"
mycmd.auto_source_mycmd_libs

function main() {
    operation1 "$@"
}

main "$@"
