#!/usr/bin/env bash
# -*- mode: shell-script; sh-shell: bash; sh-basic-offset: 4; sh-indentation: 4; coding: utf-8 -*-
# shellcheck shell=bash

if ! TESTS_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P); then
    echo >&2 "Error fetching tests directory."
    exit 1
fi
readonly TESTS_DIRECTORY

source "${TESTS_DIRECTORY}/testing-support-lib"

function test_mycmd_event_base_lib_is_loaded() {
    assertTrue 'MyCmd Lib Event Base Lib is loaded' '[ -v _MYCMD_EVENT_BASE_LIB ]'
}

function oneTimeSetUp() {
    start_tracing

    # shellcheck disable=SC2154 source=../../mycmd/mycmd-event-base-lib
    . "${MYCMD_LIB_DIRECTORY}/mycmd-event-base-lib"
}

function oneTimeTearDown() {
    cleanup_tracing
}

# shellcheck disable=SC2154 source=../vendor/shunit2
. "${TESTING_VENDOR_DIRECTORY}/shunit2"
