#!/usr/bin/env bash
# -*- mode: shell-script; sh-shell: bash; sh-basic-offset: 4; sh-indentation: 4; coding: utf-8 -*-
# shellcheck shell=bash disable=SC2317

if ! TESTS_DIRECTORY=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P); then
    echo >&2 "Error fetching tests directory."
    exit 1
fi
readonly TESTS_DIRECTORY

source "${TESTS_DIRECTORY}/testing-support-lib"

function test_pathname_lib_is_loaded() {
    assertTrue 'MyCmd Pathname Support Lib is loaded' '[ -v _MYCMD_PATHNAME_LIB ]'
}

# shellcheck disable=SC2016,SC2153,SC2154
function test_is_valid_absolute_path() {
    assertFalse '../../mycmd/mycmd-pathname-lib is not absolute' \
        'mycmd.is_valid_absolute_path ../../mycmd/mycmd-pathname-lib'

    assertFalse "${MYCMD_LIB_DIRECTORY}/../mycmd is not absolute" \
        'mycmd.is_valid_absolute_path "${MYCMD_LIB_DIRECTORY}/../mycmd"'

    assertFalse "${MYCMD_LIB_DIRECTORY}/non-existing is absolute, but doesn't exist" \
        'mycmd.is_valid_absolute_path "${MYCMD_LIB_DIRECTORY}/non-existing"'

    assertTrue "${MYCMD_LIB_DIRECTORY}/mycmd-lib is absolute and exists" \
        'mycmd.is_valid_absolute_path "${MYCMD_LIB_DIRECTORY}/mycmd-lib"'
}

# shellcheck disable=SC2016,SC2154
function test_is_valid_absolute_path_of_executed_file() {
    assertFalse '../../bin/mycmd is not an absolute path to an executable file' \
        'mycmd.is_valid_absolute_path_of_executable_file ../../bin/mycmd'

    assertFalse "${MYCMD_LIB_DIRECTORY}/../bin/mycmd is not absolute" \
        'mycmd.is_valid_absolute_path_of_executable_file "${MYCMD_LIB_DIRECTORY}/../bin/mycmd"'

    assertFalse "${MYCMD_LIB_DIRECTORY}/non-existing is absolute, but doesn't exist" \
        'mycmd.is_valid_absolute_path_of_executable_file "${MYCMD_LIB_DIRECTORY}/non-existing"'

    assertFalse "${MYCMD_LIB_DIRECTORY} is absolute, but is a directory" \
        'mycmd.is_valid_absolute_path_of_executable_file "${MYCMD_LIB_DIRECTORY}"'

    assertFalse "${MYCMD_LIB_DIRECTORY}/mycmd-lib is absolute and exists but isn't executable" \
        'mycmd.is_valid_absolute_path_of_executable_file "${MYCMD_LIB_DIRECTORY}/mycmd-lib"'

    assertTrue "${MYCMD_BIN_DIRECTORY}/mycmd is absolute, exists, and is an executable file" \
        'mycmd.is_valid_absolute_path_of_executable_file "${MYCMD_BIN_DIRECTORY}/mycmd"'
}

# shellcheck disable=SC2016
function test_is_valid_absolute_path_of_directory() {
    assertFalse '../../mycmd is not an absolute path' \
        'mycmd.is_valid_absolute_path_of_directory ../../mycmd'

    assertFalse "${MYCMD_LIB_DIRECTORY}/../mycmd is not an absolute path" \
        'mycmd.is_valid_absolute_path_of_directory "${MYCMD_LIB_DIRECTORY}/../mycmd"'

    assertFalse "${MYCMD_LIB_DIRECTORY}/non-existing is absolute, but doesn't exist" \
        'mycmd.is_valid_absolute_path_of_directory "${MYCMD_LIB_DIRECTORY}/non-existing"'

    assertFalse "${MYCMD_LIB_DIRECTORY}/mycmd-lib is absolute and exists, but not a directory" \
        'mycmd.is_valid_absolute_path_of_directory "${MYCMD_LIB_DIRECTORY}/mycmd-lib"'

    assertTrue "${MYCMD_LIB_DIRECTORY} is absolute and exists and a directory" \
        'mycmd.is_valid_absolute_path_of_directory "${MYCMD_LIB_DIRECTORY}"'
}

# shellcheck disable=SC2016,SC2312
function test_path_relative_to_directory() {
    assertFalse '../../mycmd is not an absolute path' \
        'mycmd._path_relative_to_directory ../../mycmd "${MYCMD_LIB_DIRECTORY}"'

    assertFalse '${MYCMD_LIB_DIRECTORY}/non-existing does not exist' \
        'mycmd._path_relative_to_directory "${MYCMD_LIB_DIRECTORY}/non-existing" "${MYCMD_LIB_DIRECTORY}"'

    assertFalse "${MYCMD_LIB_DIRECTORY}/../mycmd is not an absolute path" \
        'mycmd._path_relative_to_directory "${TESTS_DIRECTORY}" "${MYCMD_LIB_DIRECTORY}/../mycmd"'

    assertFalse "${MYCMD_LIB_DIRECTORY}/non-existing does not exist" \
        'mycmd._path_relative_to_directory "${TESTS_DIRECTORY}" "${MYCMD_LIB_DIRECTORY}/non-existing"'

    assertFalse "${TESTS_DIRECTORY} is not relative to ${MYCMD_LIB_DIRECTORY}" \
        'mycmd._path_relative_to_directory "${TESTS_DIRECTORY}" "${MYCMD_LIB_DIRECTORY}"'

    assertEquals "logging" \
        "$(mycmd._path_relative_to_directory "${MYCMD_LIB_DIRECTORY}/logging" "${MYCMD_LIB_DIRECTORY}")"
}

# shellcheck disable=SC2016,SC2154
function test_is_child_of_mycmd_path_directory() {
    assertFalse "${MYCMD_LIB_DIRECTORY}/non-existing does not exist" \
        'mycmd.is_child_of_mycmd_path_directory "${MYCMD_LIB_DIRECTORY}/non-existing"'

    assertFalse "${MYCMD_LIB_DIRECTORY}/../mycmd is not absolute" \
        'mycmd.is_child_of_mycmd_path_directory "${MYCMD_LIB_DIRECTORY}/../mycmd"'

    assertFalse "/tmp is not a child of a MyCmd path directory" \
        'mycmd.is_child_of_mycmd_path_directory /tmp'

    assertTrue "${MYCMD_LIB_DIRECTORY}/logging is a child of a MyCmd path directory" \
        'mycmd.is_child_of_mycmd_path_directory "${MYCMD_LIB_DIRECTORY}/logging"'

    assertTrue "${TEST_USER_LIB_DIRECTORY}/test-command-group is a child of a MyCmd path directory" \
        'mycmd.is_child_of_mycmd_path_directory "${TEST_USER_LIB_DIRECTORY}/test-command-group"'
}

# shellcheck disable=SC2016,SC2312
function test_fully_qualified_name_for_path() {
    assertFalse "${MYCMD_LIB_DIRECTORY}/non-existing does not exist" \
        'mycmd.fully_qualified_name_for_path "${MYCMD_LIB_DIRECTORY}/non-existing"'

    assertFalse "${MYCMD_LIB_DIRECTORY}/../mycmd is not absolute" \
        'mycmd.fully_qualified_name_for_path "${MYCMD_LIB_DIRECTORY}/../mycmd"'

    assertFalse "/tmp is not a child of a MyCmd path directory" \
        'mycmd.fully_qualified_name_for_path /tmp'

    assertEquals "mycmd/logging" \
        "$(mycmd.fully_qualified_name_for_path "${MYCMD_LIB_DIRECTORY}/logging")"

    assertEquals "mycmd/test-command-group" \
        "$(mycmd.fully_qualified_name_for_path "${TEST_USER_LIB_DIRECTORY}/test-command-group")"

    assertEquals "mycmd" \
        "$(mycmd.fully_qualified_name_for_path "${MYCMD_LIB_DIRECTORY}")"
}

declare -Agx walk_path_dir_counts=()
declare -Agx walk_path_file_counts=()

# shellcheck disable=SC2016,SC2154
function callback() {
    local -r full_path="${1}"
    local -r fully_qualifed_name="${2}"
    local -n dirs_ref="${3}"
    local -n files_ref="${4}"

    local -r key="${full_path}:${fully_qualifed_name}"
    walk_path_dir_counts["${key}"]=${#dirs_ref[@]}
    walk_path_file_counts["${key}"]=${#files_ref[@]}

    if [[ ! -v MYCMD_TEST_LOGGING ]]; then
        return 0
    fi

    echo "Received callback for '${full_path}' with fully-qualified name '${fully_qualifed_name}'." >>"${MYCMD_TMP_DIRECTORY}"/callback.log
    echo "Found ${#dirs_ref[@]} directories and ${#files_ref[@]} files." >>"${MYCMD_TMP_DIRECTORY}"/callback.log

    local d
    for d in "${dirs_ref[@]}"; do
        echo "Directory: ${d}" >>"${MYCMD_TMP_DIRECTORY}"/callback.log
    done

    local f
    for f in "${files_ref[@]}"; do
        echo "File: ${f}" >>"${MYCMD_TMP_DIRECTORY}"/callback.log
    done

    return 0
}

# shellcheck disable=SC2016
function test_walk_path() {
    walk_path_dir_counts=()
    walk_path_file_counts=()

    assertTrue 'walk_path runs successfully' \
        'mycmd.walk_path "mycmd" callback'

    local key
    for key in "${!TEST_WALK_PATH_DIR_COUNTS[@]}"; do
        assertEquals "Directory count for ${key}" \
            "${TEST_WALK_PATH_DIR_COUNTS[${key}]}" \
            "${walk_path_dir_counts[${key}]}"
    done

    assertTrue 'The expected number of keys were found in directory counts' \
        '[ "${#TEST_WALK_PATH_DIR_COUNTS[@]}" -eq "${#walk_path_dir_counts[@]}" ]'

    for key in "${!TEST_WALK_PATH_FILE_COUNTS[@]}"; do
        assertEquals "File count for ${key}" \
            "${TEST_WALK_PATH_FILE_COUNTS[${key}]}" \
            "${walk_path_file_counts[${key}]}"
    done

    assertTrue 'The expected number of keys were found in file counts' \
        '[ "${#TEST_WALK_PATH_FILE_COUNTS[@]}" -eq "${#walk_path_file_counts[@]}" ]'
}

declare -Agx TEST_WALK_PATH_DIR_COUNTS=()
declare -Agx TEST_WALK_PATH_FILE_COUNTS=()

# shellcheck disable=SC2034
function oneTimeSetUp() {
    setup_test_user_lib_directory
    setup_mycmd_tmp_directory
    start_tracing_and_capture_output_for_non_snapshot_tests

    # shellcheck source=../../mycmd/mycmd-pathname-lib
    . "${MYCMD_LIB_DIRECTORY}/mycmd-pathname-lib"
    mycmd.batch_init_bin

    # Hard-code values for tests
    TEST_WALK_PATH_DIR_COUNTS["${MYCMD_LIB_DIRECTORY}:mycmd"]=3
    TEST_WALK_PATH_FILE_COUNTS["${MYCMD_LIB_DIRECTORY}:mycmd"]=15

    TEST_WALK_PATH_DIR_COUNTS["${MYCMD_LIB_DIRECTORY}/create:mycmd/create"]=0
    TEST_WALK_PATH_FILE_COUNTS["${MYCMD_LIB_DIRECTORY}/create:mycmd/create"]=1

    TEST_WALK_PATH_DIR_COUNTS["${MYCMD_LIB_DIRECTORY}/logging:mycmd/logging"]=0
    TEST_WALK_PATH_FILE_COUNTS["${MYCMD_LIB_DIRECTORY}/logging:mycmd/logging"]=4

    TEST_WALK_PATH_DIR_COUNTS["${MYCMD_LIB_DIRECTORY}/shell:mycmd/shell"]=0
    TEST_WALK_PATH_FILE_COUNTS["${MYCMD_LIB_DIRECTORY}/shell:mycmd/shell"]=1

    TEST_WALK_PATH_DIR_COUNTS["${TEST_USER_LIB_DIRECTORY}:mycmd"]=2
    TEST_WALK_PATH_FILE_COUNTS["${TEST_USER_LIB_DIRECTORY}:mycmd"]=1

    TEST_WALK_PATH_DIR_COUNTS["${TEST_USER_LIB_DIRECTORY}/shell:mycmd/shell"]=1
    TEST_WALK_PATH_FILE_COUNTS["${TEST_USER_LIB_DIRECTORY}/shell:mycmd/shell"]=0

    TEST_WALK_PATH_DIR_COUNTS["${TEST_USER_LIB_DIRECTORY}/shell/extended:mycmd/shell/extended"]=0
    TEST_WALK_PATH_FILE_COUNTS["${TEST_USER_LIB_DIRECTORY}/shell/extended:mycmd/shell/extended"]=1

    TEST_WALK_PATH_DIR_COUNTS["${TEST_USER_LIB_DIRECTORY}/test-command-group:mycmd/test-command-group"]=0
    TEST_WALK_PATH_FILE_COUNTS["${TEST_USER_LIB_DIRECTORY}/test-command-group:mycmd/test-command-group"]=1
}

function oneTimeTearDown() {
    cleanup_tracing
}

# shellcheck disable=SC2154 source=../vendor/shunit2
. "${TESTING_VENDOR_DIRECTORY}/shunit2"
